[package]
name = "assembler"
authors = ["Juniper Parsons <juniperparsnips@gmail.com>"]
version = "0.1.0"
edition = "2021"

[lib]
name = "assembler"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
toml = "0.5"
